export enum Shortcut {
  pen = '1',
  eraser = '2',
  moreTools = '3',
  select = '4',
  manual = '5',
  undoredo = 'z',
  send = 'Enter',
  copy = 'd',
  delete = 'Backspace',
  selectNext = ']',
  selectPrev = '[',
  save = 's',
  merge = 'm',
  layerUp = 'ArrowUp',
  layerDown = 'ArrowDown',
  unselect = 'Escape',
  moveLeft = 'ArrowLeft',
  moveUp = 'ArrowUp',
  moveRight = 'ArrowRight',
  moveDown = 'ArrowDown',
  paste = 'v',
  flipX = 'x',
  flipY = 'y'
}
