export enum FRONTEND_ROUTES {
	draw = "draw",
	gallery = "gallery",
	connect = "connect",
	login = "login",
	home = "home",
	chat = "chat",
	profile = "profile",
	settings = "settings",
	network = "network",
	customization = "customize",
	moderation = "moderation",
	notifications = "notifications",
	competition = "competition",
	savedPosts = "saved",
}
